# SPDX-License-Identifier: GPL-2.0

ccflags-y += -I$(src)

obj-$(CONFIG_TOUCHSCREEN_CAP1296) += cap1296.o
obj-$(CONFIG_TOUCHSCREEN_FTS)	+= focaltech_touch/
obj-$(CONFIG_TOUCHSCREEN_GOODIX_BRL)	+= goodix_berlin_driver/
