# SPDX-License-Identifier: GPL-2.0

ccflags-y += -I$(src)

obj-$(CONFIG_PHY_QCOM_UFS) += phy-qcom-ufs.o

obj-$(CONFIG_PHY_QCOM_UFS_V4_CANOE) += phy-qcom-ufs-qmp-v4-canoe.o

obj-$(CONFIG_PHY_QCOM_UFS_V4_KALAMA) += phy-qcom-ufs-qmp-v4-kalama.o

obj-$(CONFIG_PHY_QCOM_UFS_V4_YUPIK) += phy-qcom-ufs-qmp-v4-yupik.o

obj-$(CONFIG_PHY_QCOM_SNPS_EUSB2) += phy-qcom-snps-eusb2.o

obj-$(CONFIG_PHY_QCOM_UFS_V4_KHAJE) += phy-qcom-ufs-qmp-v4-khaje.o

obj-$(CONFIG_PHY_QCOM_UFS_V4_LAHAINA) += phy-qcom-ufs-qmp-v4-lahaina.o

obj-$(CONFIG_PHY_QCOM_UFS_V3) += phy-qcom-ufs-qmp-v3-660.o

obj-$(CONFIG_PHY_QCOM_UFS_V4_SUN) += phy-qcom-ufs-qmp-v4-sun.o

obj-$(CONFIG_PHY_QCOM_UFS_QRBTC_SDM845) += phy-qcom-ufs-qrbtc-sdm845.o

obj-$(CONFIG_PHY_QCOM_EUSB2_REPEATER) += phy-qcom-eusb2-repeater.o

obj-$(CONFIG_PHY_QCOM_M31_EUSB2) += phy-qcom-m31-eusb2.o

obj-$(CONFIG_PHY_QCOM_QMP_COMBO) += phy-qcom-qmp-combo.o

obj-$(CONFIG_PHY_QCOM_UFS_V4_WAIPIO) += phy-qcom-ufs-qmp-v4-waipio.o

obj-$(CONFIG_PHY_QCOM_UFS_V4_CAPE) += phy-qcom-ufs-qmp-v4-cape.o

obj-$(CONFIG_PHY_QCOM_UFS_V4_DIWALI) += phy-qcom-ufs-qmp-v4-diwali.o

obj-$(CONFIG_PHY_QCOM_UFS_V4_CROW) += phy-qcom-ufs-qmp-v4-crow.o

obj-$(CONFIG_PHY_QCOM_QMP_USB) += phy-qcom-qmp-usb.o

obj-$(CONFIG_PHY_QCOM_SGMII_ETH) += phy-qcom-sgmii-eth.o

